## Topic 4 - Random Numbers 

In [4]:
import random 

In [5]:
random.randint 

<bound method Random.randint of <random.Random object at 0x7f99aa83a820>>

In [6]:
# based on the above we can generate a random integer inclusuve of 10 and 20 
random.randint(10,20)

16

In [7]:
L = [random.randint(1,10) for i in range(100)]
print(L[:10])

[8, 8, 7, 1, 9, 3, 3, 2, 6, 5]


In [1]:
import numpy as np 

In [8]:
print(L[:10])

[8, 8, 7, 1, 9, 3, 3, 2, 6, 5]


In [9]:
#List of car makes 
makes = ['Toyota','Skoda','Ford','BMW']

In [10]:
#select one at random
random.choice(makes)

'Skoda'

In [11]:
#Select ten random choices
random.choices(makes,k=10)

['Skoda',
 'Toyota',
 'BMW',
 'Ford',
 'Toyota',
 'BMW',
 'Skoda',
 'Ford',
 'Skoda',
 'BMW']

In [12]:
random.shuffle(makes)

In [13]:
print(makes)

['Ford', 'Toyota', 'BMW', 'Skoda']


In [14]:
random.sample(makes,k=2)

['BMW', 'Skoda']

In [15]:
random.random()

0.5353439896388688

In [16]:
random.uniform(0.0,100.0)

96.545711070657

## Import Numpy ( done above) 

In [17]:
#import numpy as np and matplotlib as plt 
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
import matplotlib as plt 

In [24]:
# Construct a new Generator with the default BitGenerator (PCG64)
rng = np.random.default_rng()
# Return random floats in the half-open interval [0.0, 1.0).
rng.random(10)

array([0.36725699, 0.35871874, 0.34219038, 0.49482801, 0.36772753,
       0.48082269, 0.50796408, 0.7138254 , 0.04893318, 0.66197467])

In [26]:
# Generate numbers from a standard Normal distribution (mean=0, stdev=1).
rng.standard_normal(10) 

array([-0.83123217, -1.684029  , -0.54184951,  2.14510006,  0.79500605,
       -1.20150789, -0.74196678,  0.45395035,  0.11709543, -0.97429836])

In [28]:
# Return random integers from low (inclusive) to high (exclusive), or if endpoint=True, low (inclusive) to high (inclusive).
rng.integers(low=0, high=10, size=15)

array([4, 8, 2, 9, 5, 6, 5, 2, 7, 7, 6, 4, 8, 2, 7])

## END